# Generated by Django 5.2.6 on 2026-01-30 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the area', max_length=100)),
                ('latitude', models.FloatField(help_text='Latitude of the center point')),
                ('longitude', models.FloatField(help_text='Longitude of the center point')),
                ('radius_km', models.FloatField(default=10.0, help_text='Radius of the area in kilometers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_date', models.DateTimeField(help_text='Date and time when the image was captured')),
                ('cloud_coverage', models.FloatField(help_text='Cloud coverage percentage (0-100)')),
                ('satellite_name', models.CharField(default='Sentinel-2', max_length=50)),
                ('image_id', models.CharField(help_text='Unique identifier from the satellite provider', max_length=255, unique=True)),
                ('metadata_json', models.JSONField(blank=True, help_text='Additional metadata from the provider', null=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='satellite_data.areaofinterest')),
            ],
            options={
                'ordering': ['-acquisition_date'],
            },
        ),
    ]
