# Generated by Django 5.2.6 on 2026-01-30 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_file_path', models.CharField(help_text='Path to the processed GeoTIFF/Array file', max_length=255)),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
                ('ndvi_mean', models.FloatField(blank=True, help_text='Average NDVI value for quick reference', null=True)),
                ('processing_metadata', models.JSONField(default=dict, help_text='Details on masking, normalization, etc.')),
                ('satellite_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_version', to='satellite_data.satelliteimage')),
            ],
        ),
    ]
