# Generated by Django 5.2.6 on 2026-01-30 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_data', '0002_processedimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedimage',
            old_name='processing_metadata',
            new_name='processed_metadata',
        ),
        migrations.CreateModel(
            name='VegetationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_ndvi', models.FloatField(help_text='Average NDVI value for the area')),
                ('forest_cover_percentage', models.FloatField(help_text='Percentage of pixels classified as forest (NDVI > 0.5)')),
                ('heatmap_file_path', models.CharField(help_text='Path to the visual NDVI heatmap file', max_length=255)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('processed_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vegetation_analysis', to='satellite_data.processedimage')),
            ],
        ),
    ]
