# Generated by Django 5.2.6 on 2026-01-30 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_data', '0003_rename_processing_metadata_processedimage_processed_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeforestationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forest_loss_hectares', models.FloatField(help_text='Estimated area of forest lost in hectares')),
                ('loss_percentage', models.FloatField(help_text='Percentage of forest lost relative to previous state')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('loss_map_path', models.CharField(blank=True, help_text='Path to the visual change map', max_length=255, null=True)),
                ('analysis_after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_as_after', to='satellite_data.vegetationanalysis')),
                ('analysis_before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_as_before', to='satellite_data.vegetationanalysis')),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='satellite_data.areaofinterest')),
            ],
        ),
    ]
