# Generated by Django 5.2.6 on 2026-01-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_data', '0004_deforestationalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='satelliteimage',
            name='gee_id',
            field=models.CharField(blank=True, help_text='Google Earth Engine Asset ID', max_length=255, null=True),
        ),
    ]
