# Generated by Django 5.2.6 on 2026-01-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_data', '0005_satelliteimage_gee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deforestationalert',
            name='loss_map_path',
            field=models.TextField(blank=True, help_text='Path or URL to the visual change map', null=True),
        ),
        migrations.AlterField(
            model_name='vegetationanalysis',
            name='heatmap_file_path',
            field=models.TextField(help_text='Path or URL to the visual NDVI heatmap'),
        ),
    ]
